### PR TITLE
Add support to vivoactive 3 series devices

### PR DESCRIPTION
**Pull request by aleung**
Thanks for developed the great app.

It works on Vivoactive 3 device with very little change:
- Crop the icon
- Fix some warnings

### CODE REVIEW

**Review by andan67 — APPROVED** [review]
Thank you again for your contribution.
I'm now starting to build and deploy a new app version for the store with your changes included.
If you plan to include more changes, feel free to post further pull requests.

**Comment by andan67** [comment]
I've run the new code in the ConnectIQ simulator using the Vovoactive 3 device and noticed that some portions of the screen are cut-off (see attached screenshots). I guess that this will also happen on the real device. Do you intend to make further adoptions for the round screen of the Vivoactive device to fix this issue?

Vivoactive_3_menu
Vivoactive_3_track

**Comment by aleung** [comment]
@andan67 No, it doesn't happen on real device. The text display on simulator is a bit larger than real one.

After this MR, I had done code refactoring and improvement on how operates on a touch screen. 

Perhaps you could first have a look at it on my dev branch: https://github.com/aleung/wormnav/commits/dev and let me know your general feeling. Because I have changed a lot, and coding/design style is sometimes personal favor.

**Comment by andan67** [comment]
@aleung: Great to see you so active.
At a first glance your changes and style look reasonable to me.

My only concern is that functionality gets broken or that the resource demands exceed the limits of the FR235 (especially memory and performance). I think in that respect the Vivoactive 3 device is much more powerful.

So feel free to issue a new pull request when you think your changes are mature enough. I could create a new branch for this. 

BTW: Any idea of how to fix the text font size issue with the simulator?

**Pull request merged**
